# A simple script to auto-generate .txt game lists for Cheats Manager
# made by Bucanero

name: Push commit

on:
  push:
    branches: [ main ]

jobs:
  gamelist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Normalize json data
        run: python .ci/normalize-json.py

      - name: Create list files
        run: |
          clang .ci/list_files.c
          ./a.out json '"name"' > json.txt
          ./a.out shn Game > shn.txt
          mkdir xml
          mv mc4/*.xml xml/
          ./a.out xml Game > mc4.txt
          mv xml/* mc4/
          rmdir xml
          git config --global user.name 'kmeps4'
          git config --global user.email 'kmeps4@users.noreply.github.com'

      - name: Commit normalized json data
        run: |
          git add json/*.json
          git commit -m "Normalize json data" || true

      - name: Commit list files
        run: |
          git add json.txt
          git add shn.txt
          git add mc4.txt
          git commit -m "Cheat lists update" || true
          git push || true
